export const images =  [
    {
        largeURL: './src/assets/images/img (1).jpg',
        thumbnailURL: './src/assets/images/img (1).jpg',
        alt: "Taller de electromecánica",
        width: 1600,
        height: 1200,
    },
    {
        largeURL: './src/assets/images/img (2).jpg',
        thumbnailURL: './src/assets/images/img (2).jpg',
        alt: "Entrada principal",
        width: 1600,
        height: 900,
    },
    {
        largeURL: './src/assets/images/img (3).jpg',
        thumbnailURL: './src/assets/images/img (3).jpg',
        alt: "Laboratorio de programación",
        width: 1600,
        height: 900,
    },
    {
        largeURL: './src/assets/images/img (4).jpg',
        thumbnailURL: './src/assets/images/img (4).jpg',
        alt: "Cuadros honorarios",
        width: 1600,
        height: 900,
    },
    {
        largeURL: './src/assets/images/img (5).jpg',
        thumbnailURL: './src/assets/images/img (5).jpg',
        alt: "Entrada al patio",
        width: 1600,
        height: 900,
    },
    {
        largeURL: './src/assets/images/img (6).jpg',
        thumbnailURL: './src/assets/images/img (6).jpg',
        alt: "Taller de carpintería",
        width: 1600,
        height: 1200,
    },
    {
        largeURL: './src/assets/images/img (7).jpg',
        thumbnailURL: './src/assets/images/img (7).jpg',
        alt: "Sección de tornos mecánicos",
        width: 1200,
        height: 1600,
    },
    {
        largeURL: './src/assets/images/img (8).jpg',
        thumbnailURL: './src/assets/images/img (8).jpg',
        alt: "Patio del colegio",
        width: 1600,
        height: 900,
    },
    {
        largeURL: './src/assets/images/img (9).jpg',
        thumbnailURL: './src/assets/images/img (9).jpg',
        alt: "Taller de herrería",
        width: 1600,
        height: 1200,
    },
    {
        largeURL: './src/assets/images/img (10).jpg',
        thumbnailURL: './src/assets/images/img (10).jpg',
        alt: "Fundador del colegio",
        width: 1600,
        height: 900,
    },
    {
        largeURL: './src/assets/images/img (11).jpg',
        thumbnailURL: './src/assets/images/img (11).jpg',
        alt: "Taller de electromecánica",
        width: 1600,
        height: 1200,
    }
    ,
    {
        largeURL: './src/assets/images/img (12).jpg',
        thumbnailURL: './src/assets/images/img (12).jpg',
        alt: "Cancha de fútbol 11",
        width: 1600,
        height: 900,
    },
    {
        largeURL: './src/assets/images/img (13).jpg',
        thumbnailURL: './src/assets/images/img (13).jpg',
        alt: "Edificio de teoría",
        width: 1600,
        height: 900,
    },
    {
        largeURL: './src/assets/images/img (14).jpg',
        thumbnailURL: './src/assets/images/img (14).jpg',
        alt: "Laboratorio de programación",
        width: 1600,
        height: 900,
    },
    {
        largeURL: './src/assets/images/img (15).jpg',
        thumbnailURL: './src/assets/images/img (15).jpg',
        alt: "Laboratorio de neumática",
        width: 1600,
        height: 1200,
    },
    {
        largeURL: './src/assets/images/img (16).jpg',
        thumbnailURL: './src/assets/images/img (16).jpg',
        alt: "Patio del colegio",
        width: 1600,
        height: 900,
    },
    {
        largeURL: './src/assets/images/img (17).jpg',
        thumbnailURL: './src/assets/images/img (17).jpg',
        alt: "Taller de carpintería",
        width: 1600,
        height: 1200,
    },
    {
        largeURL: './src/assets/images/img (18).jpg',
        thumbnailURL: './src/assets/images/img (18).jpg',
        alt: "Taller de herrería",
        width: 1600,
        height: 1200,
    },
    {
        largeURL: './src/assets/images/img (19).jpg',
        thumbnailURL: './src/assets/images/img (19).jpg',
        alt: "Patio del colegio",
        width: 1600,
        height: 900,
    },
    {
        largeURL: './src/assets/images/img (20).jpg',
        thumbnailURL: './src/assets/images/img (20).jpg',
        alt: "Aula de taller",
        width: 1600,
        height: 1200,
    }
]